# Generated by Django 6.0.2 on 2026-02-24 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('ALTERNATE', 'Alternate Days'), ('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('WEEKENDS', 'Weekends (Sat-Sun)')], default='DAILY', max_length=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.product')),
            ],
        ),
    ]
